API/Admin/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using UnnoticedAPI.Models.Common;
using UnnoticedAPI.Models.Domain.Gallery;
using UnnoticedAPI.Models.View;
using UnnoticedAPI.Utils.Domain;
using UnnoticedAPI.Utils.Infrastructure;
using UnnoticedAPI.Utils.View;

namespace UnnoticedAPI.Controllers.MVC
{
    public class GalleryController : Controller
    {
        private static readonly int imagePageLimit = 10;
        private static readonly int imageSetPageLimit = 20;
        private static readonly object lockObj = new object();

        [HttpGet]
        [IsValidAuth]
        public ActionResult ProcessImages()
        {
            return View(GalleryAdminRepo.GetFirstUnprocessedImage());
        }

        [HttpPost]
        public ActionResult ProcessImages(ImageAdminDto dto, string authPassPhrase)
        {
            try
            {
                if (CommonUtils.IsValidAuth(HttpContext) || CommonUtils.IsValidAdminPhrase(authPassPhrase))
                    GalleryAdminRepo.UpdateImage(dto);

                if (!CommonUtils.IsValidAuth(HttpContext))
                    return RedirectToAction("Index", "Home");

                return RedirectToAction("ProcessImages");
            }
            catch (UnnoticedException ex)
            {
                TempData["neba_error"] = ex.Message;
                return View(dto);
            }
        }

        [HttpPost]
        public EmptyResult UploadImage(HttpPostedFileBase image)
        {
            if (!CommonUtils.IsValidAuth(HttpContext))
                return new EmptyResult();
            if (image != null && image.ContentLength > 0 && image.ContentType.Equals("image/jpeg"))
            {
                string fileName = System.IO.Path.GetFileName(image.FileName).Replace(" ", string.Empty);
                string serverLocalPathToRawUploads = HttpContext.Server.MapPath("~/Content/ImageUploads/Pending") + "/";
                System.IO.Directory.CreateDirectory(serverLocalPathToRawUploads);
                string filePath = serverLocalPathToRawUploads + fileName;
                filePath = filePath.Replace(".jpeg", ".jpg").Replace(".jpe", ".jpg");
                for (int j = 2; System.IO.File.Exists(filePath); j++)
                {
                    string tmpFilePath = filePath.Insert(filePath.LastIndexOf('.'), "." + j + ".jpg");
                    if (!System.IO.File.Exists(tmpFilePath))
                        filePath = tmpFilePath;
                }
                image.SaveAs(filePath);
            }
            return new EmptyResult();
        }

        [HttpPost]
        [IsValidAuth]
        public ActionResult UploadImages()
        {
            return RedirectToAction("ProcessUploadedImages");
        }

        [HttpGet]
        [IsValidAuth]
        public ActionResult ProcessUploadedImages()
        {
            if (Monitor.TryEnter(lockObj, 500))
            {
                try
                {
                    string serverLocalPathToRawUploads = HttpContext.Server.MapPath("~/Content/ImageUploads/Pending") + "/";
                    System.IO.DirectoryInfo rawDir = System.IO.Directory.CreateDirectory(serverLocalPathToRawUploads);
                    IEnumerable<System.IO.FileInfo> listOfFiles = rawDir.GetFiles().Where(fI => fI.Extension.ToLower().Contains("jpg") || fI.Extension.ToLower().Contains("jpe") || fI.Extension.ToLower().Contains("jpeg"));
                    foreach (System.IO.FileInfo imgFileInfo in listOfFiles)
                    {
                        string fileName = System.IO.Path.GetFileName(imgFileInfo.Name).Replace(" ", string.Empty);
                        string serverLocalPathToUploads = HttpContext.Server.MapPath("~/Content/ImageUploads/Processed") + "/";
                        string imagesDir = serverLocalPathToUploads + DateTime.UtcNow.ToString("MMMddyyyy") + "/";
                        System.IO.Directory.CreateDirectory(imagesDir);
                        string filePath = imagesDir + fileName;
                        filePath = filePath.Replace(".jpeg", ".jpg").Replace(".jpe", ".jpg");
                        for (int j = 2; System.IO.File.Exists(filePath); j++)
                        {
                            string tmpFilePath = filePath.Replace(".jpg", "." + j + ".jpg");
                            if (!System.IO.File.Exists(tmpFilePath))
                                filePath = tmpFilePath;
                        }
                        System.IO.File.Move(imgFileInfo.FullName, filePath);
                        using (System.Drawing.Image image = System.Drawing.Image.FromFile(filePath))
                        {
                            using (System.Drawing.Image cropThumb = ImageUtils.CropToThumb(image))
                            {
                                cropThumb.Save(filePath.Replace(".jpg", ".thumb.jpg"), System.Drawing.Imaging.ImageFormat.Jpeg);
                            }
                            using (System.Drawing.Image cropDisp = ImageUtils.CropToDisplay(image))
                            {
                                cropDisp.Save(filePath.Replace(".jpg", ".disp.jpg"), System.Drawing.Imaging.ImageFormat.Jpeg);
                            }

                            filePath = filePath.Replace(serverLocalPathToUploads, SiteConfigUtils.GetSiteRootUrl() + "Content/ImageUploads/Processed/");
                            Image toAdd = new Image
                            {
                                Aperture = ImageUtils.GetAperture(image),
                                Camera = ImageUtils.GetCamera(image),
                                Caption = "Uncaptioned",
                                DisplayPath = filePath.Replace(".jpg", ".disp.jpg"),
                                ThumbPath = filePath.Replace(".jpg", ".thumb.jpg"),
                                FilePath = filePath,
                                Exposure = ImageUtils.GetExposure(image),
                                FocalLength = ImageUtils.GetFocalLength(image),
                                FocalLengthIn35mm = ImageUtils.GetFocalLengthIn35mm(image),
                                Landscape = image.Width > image.Height,
                                Iso = ImageUtils.GetISO(image),
                                TakenAt = ImageUtils.GetDateTimeTaken(image)
                            };
                            GalleryAdminRepo.AddImage(toAdd);
                        }
                    }
                }
                finally
                {
                    Monitor.Exit(lockObj);
                }
            }
            return RedirectToAction("ProcessImages");
        }

        [HttpGet]
        [IsValidAuth]
        public ActionResult EditImage(int id, int page = 1, int setId = -1)
        {
            return View(new ImageEditModel { ImgDto = GalleryAdminRepo.GetImage(id), Id = id, Page = page, SetId = setId });
        }

        [HttpPost]
        public ActionResult EditImage(ImageEditModel dto, string authPassPhrase)
        {
            try
            {
                if (CommonUtils.IsValidAuth(HttpContext) || CommonUtils.IsValidAdminPhrase(authPassPhrase))
                    GalleryAdminRepo.UpdateImage(dto.ImgDto);

                if (!CommonUtils.IsValidAuth(HttpContext))
                    return RedirectToAction("Index", "Home");

                string redirAction = "Images";
                RouteValueDictionary routeData = new RouteValueDictionary();
                if (dto.SetId > 0)
                {
                    redirAction = "ManageImageSet";
                    routeData.Add("id", dto.SetId);
                }
                if (dto.Page > 1)
                    routeData.Add("page", dto.Page);

                return RedirectToAction(redirAction, routeData);
            }
            catch (UnnoticedException ex)
            {
                TempData["neba_error"] = ex.Message;
                return View(dto);
            }
        }

        [HttpGet]
        [IsValidAuth]
        public ActionResult DeleteImage(int id, int page = 1, int setId = -1)
        {
            return View(new ImageDeleteModel { Id = id, Page = page, SetId = setId });
        }

        [HttpPost]
        public ActionResult DeleteImageConf(int id, int page, int setId, string authPassPhrase)
        {
            try
            {
                if (CommonUtils.IsValidAuth(HttpContext) || CommonUtils.IsValidAdminPhrase(authPassPhrase))
                {
                    DeleteImageFromDisk(id);
                    GalleryAdminRepo.DeleteImage(id);
                }

                if (!CommonUtils.IsValidAuth(HttpContext))
                    return RedirectToAction("Index", "Home");

                string redirAction = "Images";
                RouteValueDictionary routeData = new RouteValueDictionary();
                if (setId > 0)
                {
                    redirAction = "ManageImageSet";
                    routeData.Add("id", setId);
                }
                if (page > 1)
                {
                    int maxPage = setId > 0 ? GalleryAdminRepo.GetImagesOfSetMaxPage(setId, imagePageLimit) : GalleryAdminRepo.GetImagesMaxPage(imagePageLimit);
                    if (page > maxPage)
                        page = maxPage;
                    routeData.Add("page", page);
                }

                return RedirectToAction(redirAction, routeData);
            }
            catch (UnnoticedException ex)
            {
                TempData["neba_error"] = ex.Message;
                return RedirectToAction("DeleteImage", new { id = id });
            }
        }

        [NonAction]
        private void DeleteImageFromDisk(int id)
        {
            ImageAdminDto temp = GalleryAdminRepo.GetImage(id);

API/Admin/Views/CreateImageSet.cshtml
@{
    ViewBag.Title = "Create Image Set";
    Layout = "~/Views/Shared/_TwoColumn.cshtml";
}
@Html.Partial("_ImageSetForm")

API/Admin/Views/DeleteImage.cshtml
@model ImageDeleteModel
@{
    ViewBag.Title = "Delete Image";
    Layout = "~/Views/Shared/_TwoColumn.cshtml";
}
@using (Html.BeginForm("DeleteImageConf", "Gallery"))
{
    <div id="dataloadingbox">
        @Html.Hidden("authPassPhrase", CommonUtils.GenerateTimeBasedHashAdminPhrase(DateTime.Now.ToUniversalTime()))
        @Html.Hidden("id", Model.Id)
        @Html.Hidden("page", Model.Page)
        @Html.Hidden("setId", Model.SetId)
        <input type="submit" class="pink button" id="deleteconf" value="Delete" />
    </div>
}

API/Admin/Views/DeleteImageSet.cshtml
@model int
@{
    ViewBag.Title = "Delete Image Set";
    Layout = "~/Views/Shared/_TwoColumn.cshtml";
}
@using (Html.BeginForm("DeleteImageSetConf", "Gallery"))
{
    <div id="dataloadingbox">
        @Html.Hidden("authPassPhrase", CommonUtils.GenerateTimeBasedHashAdminPhrase(DateTime.Now.ToUniversalTime()))
        @Html.Hidden("id", Model)
        <input type="submit" class="pink button" id="deleteconf" value="Delete" />
    </div>
}

API/Admin/Views/EditImage.cshtml
@model ImageEditModel
@{
    ViewBag.Title = "Edit Image";
    Layout = "~/Views/Shared/_TwoColumn.cshtml";
}
<div class="contentbox" id="imagebody">
    <div class="contentboxbody">
        <img src="@Url.Content(Model.ImgDto.DisplayPath)" alt="" />
    </div>
    <div class="contentboxend" id="imagecaption">
        @Model.ImgDto.Caption
    </div>
</div>
@using (Html.BeginForm())
{
    <div class="contentbox">
        <div class="contentboxtop">
            <span class="boxtitle">Image</span>
        </div>
        <div class="contentboxbody">
            @Html.Hidden("authPassPhrase", CommonUtils.GenerateTimeBasedHashAdminPhrase(DateTime.Now.ToUniversalTime()))
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.Page)
            @Html.HiddenFor(m => m.SetId)
            @Html.HiddenFor(m => m.ImgDto.Id)
            @Html.HiddenFor(m => m.ImgDto.FilePath)
            @Html.HiddenFor(m => m.ImgDto.ThumbPath)
            @Html.HiddenFor(m => m.ImgDto.DisplayPath)
            @Html.LabelFor(m => m.ImgDto.Caption, new { @class = "fieldlabel" })
            @Html.TextBoxFor(m => m.ImgDto.Caption, new { @class = "fieldfield" })
            @Html.LabelFor(m => m.ImgDto.TakenAt, new { @class = "fieldlabel" })
            @Html.TextBoxFor(m => m.ImgDto.TakenAt, new { @class = "fieldfield" })
            @Html.LabelFor(m => m.ImgDto.Camera, new { @class = "fieldlabel" })
            @Html.TextBoxFor(m => m.ImgDto.Camera, new { @class = "fieldfield" })
            @Html.LabelFor(m => m.ImgDto.Aperture, new { @class = "fieldlabel" })
            @Html.TextBoxFor(m => m.ImgDto.Aperture, new { @class = "fieldfield" })
            @Html.LabelFor(m => m.ImgDto.Exposure, new { @class = "fieldlabel" })
            @Html.TextBoxFor(m => m.ImgDto.Exposure, new { @class = "fieldfield" })
            @Html.LabelFor(m => m.ImgDto.Iso, new { @class = "fieldlabel" })
            @Html.TextBoxFor(m => m.ImgDto.Iso, new { @class = "fieldfield" })
            @Html.LabelFor(m => m.ImgDto.FocalLength, new { @class = "fieldlabel" })
            @Html.TextBoxFor(m => m.ImgDto.FocalLength, new { @class = "fieldfield" })
            @Html.LabelFor(m => m.ImgDto.FocalLengthIn35mm, new { @class = "fieldlabel" })
            @Html.TextBoxFor(m => m.ImgDto.FocalLengthIn35mm, new { @class = "fieldfield" })
            @Html.LabelFor(m => m.ImgDto.ImageSetId, new { @class = "fieldlabel" })
            @Html.DropDownListFor(m => m.ImgDto.ImageSetId, GalleryAdminRepo.GenerateSelectListOfSets(), new { @class = "fieldfield" })
        </div>
        <div class="contentboxend">
            <input type="submit" class="green button" value="Submit" />
        </div>
    </div>
}

API/Admin/Views/EditImageSet.cshtml
@model ImageSetDto
@{
    ViewBag.Title = "Edit Image Set";
    Layout = "~/Views/Shared/_TwoColumn.cshtml";
}
@Html.Partial("_ImageSetForm", Model)

API/Admin/Views/ImageSets.cshtml
@model ImageSetListModel
@{
    ViewBag.Title = "Image Sets";
    Layout = "~/Views/Shared/_TwoColumn.cshtml";
}
<div class="contentbox">
    <div class="contentboxtop">
        <span class="boxtitle">Image Sets</span>
    </div>
    <div class="contentboxbody">
        @if (Model.ListData.Count() > 0)
        {
            <table class="admintable">
                <thead>
                    <tr>
                        <td>Name</td>
                        <td>Count</td>
                        <td>Private</td>
                        <td>Action</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (ImageSetDto iS in Model.ListData)
                    {
                        <tr>
                            <td>@iS.Name</td>
                            <td>@iS.Count</td>
                            <td>@iS.Private</td>
                            <td>@Html.ActionLink("Manage", "ManageImageSet", new { id = iS.Id }, new { @class = "actionlink" })@Html.ActionLink("Edit", "EditImageSet", new { id = iS.Id }, new { @class = "actionlink" })@Html.ActionLink("Delete", "DeleteImageSet", new { id = iS.Id }, new { @class = "actionlink" })</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <span id="adminliststatus">No image sets</span>
        }
    </div>
    <div class="contentboxend">
        <a href="@Url.Action("CreateImageSet")" class="gray button">Create Image Set</a>
    </div>
</div>
@section Pagination{
    @if (Model.Page > 1)
    {
        <a class="paging prev" id="pagingprev" href="@Url.Action("ImageSets", new { page = Model.Page - 1 })"><span>Previous</span></a>
    }
    @if (Model.MaxPage > Model.Page)
    {
        <a class="paging next" id="pagingnext" href="@Url.Action("ImageSets", new { page = Model.Page + 1 })"><span>Next</span></a>
    }
}

API/Admin/Views/ManageImageSet.cshtml
@model ImageListModel
@{
    ViewBag.Title = "Manage Image Set";
    Layout = "~/Views/Shared/_TwoColumn.cshtml";
}
@if (Model.ListData.Count() > 0)
{
    <div class="contentbox">
        <div class="contentboxtop">
            <span class="boxtitle">Image Set</span>
        </div>
        <div class="contentboxbody">
            <table class="admintable">
                <thead>
                    <tr>
                        <td>Thumbnail</td>
                        <td>Caption</td>
                        <td>Action</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (ImageAdminDto i in Model.ListData)
                    {
                        <tr>
                            <td><img src="@i.ThumbPath" class="adminimagelist" alt="" /></td>
                            <td>@i.Caption</td>
                            <td>@Html.ActionLink("Edit", "EditImage", "Gallery", new { id = i.Id, page = Model.Page, setId = Model.ImageSetId }, new { @class = "actionlink" })@Html.ActionLink("Delete", "DeleteImage", "Gallery", new { id = i.Id, page = Model.Page, setId = Model.ImageSetId }, new { @class = "actionlink" })</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
        <div class="contentboxend"></div>
    </div>
}
else
{
    <div id="dataloadingbox">No images in this set</div>
}
@section Pagination{
    @if (Model.Page > 1)
    {
        <a class="paging prev" id="pagingprev" href="@Url.Action("ManageImageSet", new { page = Model.Page - 1, id = Model.ImageSetId })"><span>Previous</span></a>
    }
    @if (Model.MaxPage > Model.Page)
    {
        <a class="paging next" id="pagingnext" href="@Url.Action("ManageImageSet", new { page = Model.Page + 1, id = Model.ImageSetId })"><span>Next</span></a>
    }
}

API/Admin/Views/ProcessImages.cshtml
@model ImageAdminDto
@{
    ViewBag.Title = "Upload Images";
    Layout = "~/Views/Shared/_TwoColumn.cshtml";
}
@if (Model != null)
{
    @Html.Partial("_ImageForm", Model)
}
else
{
    <div id="dataloadingbox">No pending images</div>
    
    using (Html.BeginForm("UploadImages", "Gallery", FormMethod.Post, new { id = "uploadform" }))
    {
    <div class="contentbox">
        <div class="contentboxtop">
            <span class="boxtitle">Upload Images</span>
        </div>
        <div class="contentboxbody">
            <input id="uploadfilelist" class="fieldfield" name="images" type="file" multiple="multiple" accept="image/jpeg" />
        </div>
        <div class="contentboxend">
            <input type="submit" class="green button" value="Upload" id="uploadbtn" onclick="uploadProcess()" />
        </div>
    </div>
    }
}
@section HeaderInsert{
    <script type="text/javascript">
        var uploadProcess = function () {
            var upload_btn = $('#uploadbtn');
            upload_btn.attr('value', 'Uploading...');
            upload_btn.attr('disabled', 'disabled');
            var upload_file_list = $('#uploadfilelist');
            var files_array = upload_file_list[0].files;
            upload_file_list.attr('disabled', 'disabled');
            for (i = 0; i < files_array.length; i++) {
                var uploadReq = new XMLHttpRequest();
                var filedata = new FormData();
                filedata.append('image', files_array[i]);
                uploadReq.open("POST", '@Url.Action("UploadImage")', false);
                uploadReq.send(filedata);
            }
            $('#uploadform').submit();
        }
    </script>
}

API/Admin/Views/_HeaderFooter.cshtml
@{
    bool HasError = TempData["neba_error"] != null;
}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@SiteConfigUtils.GetTitlePrefix()@ViewBag.Title</title>
    <link rel="shortcut icon" href="@Url.Content("~/favicon.ico")" />
    <link href="@Url.Content("~/Content/css/reset.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/fontfaces.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/style.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/adminstyle.css")" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="@Url.Content("~/Content/js/MarkdownDeep.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/jquery-1.8.2.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/js/admincommon.js")"></script>
    @RenderSection("HeaderInsert", false)
    <script type="text/javascript">
        @RenderSection("JsVarInsert", false)
        $(window).load(function () {
            @RenderSection("JsOnLoadInsert", false)
            $.getJSON('@Url.RouteUrl("DefaultApi", new { httproute = "", controller = "Image", action = "GetRandomBackgroundImage" })', setBackgroundGiven);
        });
    </script>
</head>
<body id="home">
    <div id="bgloadingoverlay"></div>
    <div id="bgoverlay"></div>
    <div id="shadeoverlay"></div>
    @if (HasError)
    {<div id="errornotify">@TempData["neba_error"]</div>}
    <div id="wrapper">
        <div id="header">
            <div id="headertop">
                <a id="logo" href="@Url.Action("Index", "Home")">
                    <img src="@Url.Content("~/Content/images/header/logo.png")" alt=""/></a>
            </div>
            <div id="headermenu">
                <a class="active" href="@Url.Action("Index", "Home")"><span>Home</span></a>
            </div>
        </div>
        @RenderBody()
    </div>
    <div id="footer">©2014 Wanfung Joshua Lee | <a href="@Url.Action("ClearAuth", "Home")">Clear Auth</a> | <a id="hidetoggle" onclick="toggleWrapper()">Toggle Content Visibility</a></div>
</body>
</html>

API/Admin/Views/_ImageForm.cshtml
@model ImageAdminDto
<div class="contentbox" id="imagebody">
    <div class="contentboxbody">
        <img src="@Url.Content(Model.DisplayPath)" alt="" />
    </div>
    <div class="contentboxend" id="imagecaption">
        @Model.Caption
    </div>
</div>
@using (Html.BeginForm())
{
    <div class="contentbox">
        <div class="contentboxtop">
            <span class="boxtitle">Image</span>
        </div>
        <div class="contentboxbody">
            @Html.Hidden("authPassPhrase", CommonUtils.GenerateTimeBasedHashAdminPhrase(DateTime.Now.ToUniversalTime()))
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.FilePath)
            @Html.HiddenFor(m => m.ThumbPath)
            @Html.HiddenFor(m => m.DisplayPath)
            @Html.LabelFor(m => m.Caption, new { @class = "fieldlabel" })
            @Html.TextBoxFor(m => m.Caption, new { @class = "fieldfield" })
            @Html.LabelFor(m => m.TakenAt, new { @class = "fieldlabel" })
            @Html.TextBoxFor(m => m.TakenAt, new { @class = "fieldfield" })
            @Html.LabelFor(m => m.Camera, new { @class = "fieldlabel" })
            @Html.TextBoxFor(m => m.Camera, new { @class = "fieldfield" })
            @Html.LabelFor(m => m.Aperture, new { @class = "fieldlabel" })
            @Html.TextBoxFor(m => m.Aperture, new { @class = "fieldfield" })
            @Html.LabelFor(m => m.Exposure, new { @class = "fieldlabel" })
            @Html.TextBoxFor(m => m.Exposure, new { @class = "fieldfield" })
            @Html.LabelFor(m => m.Iso, new { @class = "fieldlabel" })
            @Html.TextBoxFor(m => m.Iso, new { @class = "fieldfield" })
            @Html.LabelFor(m => m.FocalLength, new { @class = "fieldlabel" })
            @Html.TextBoxFor(m => m.FocalLength, new { @class = "fieldfield" })
            @Html.LabelFor(m => m.FocalLengthIn35mm, new { @class = "fieldlabel" })
            @Html.TextBoxFor(m => m.FocalLengthIn35mm, new { @class = "fieldfield" })
            @Html.LabelFor(m => m.ImageSetId, new { @class = "fieldlabel" })
            @Html.DropDownListFor(m => m.ImageSetId, GalleryAdminRepo.GenerateSelectListOfSets(), new { @class = "fieldfield" })
        </div>
        <div class="contentboxend">
            <input type="submit" class="green button" value="Submit" />
        </div>
    </div>
}

API/Admin/Views/_ImageSetForm.cshtml
@model ImageSetDto
@using (Html.BeginForm())
{
    <div class="contentbox">
        <div class="contentboxtop">
            <span class="boxtitle">Image Set</span>
        </div>
        <div class="contentboxbody">
            @Html.Hidden("authPassPhrase", CommonUtils.GenerateTimeBasedHashAdminPhrase(DateTime.Now.ToUniversalTime()))
            @Html.HiddenFor(m => m.Id)
            @Html.LabelFor(m => m.Name, new { @class = "fieldlabel" })
            @Html.TextBoxFor(m => m.Name, new { @class = "fieldfield" })
            @Html.LabelFor(m => m.Private, new { @class = "fieldlabel" })
            @Html.CheckBoxFor(m => m.Private)
        </div>
        <div class="contentboxend">
            <input type="submit" class="green button" value="Submit" />
        </div>
    </div>
}

API/Admin/Views/_TwoColumn.cshtml
@{
    Layout = "~/Views/Shared/_HeaderFooter.cshtml";
}
<div class="pagewrap left side">
    <div class="sidebox" id="navbox">
        <div class="sideboxtitle">Navigation</div>
        <div class="sideboxbody">
            <a href="@Url.Action("BlogPosts", "Blog")"><span>Manage Blog Posts</span></a>
            <a href="@Url.Action("BlogCategories", "Blog")"><span>Manage Blog Categories</span></a>
            <a href="@Url.Action("ImageSets", "Gallery")"><span>Manage Image Sets</span></a>
            <a href="@Url.Action("ProcessUploadedImages", "Gallery")"><span>Upload/Process Images</span></a>
            @RenderSection("Pagination", false)
            <a class="paging prev" id="pagingprev" href="#" style="display: none"><span>Previous</span></a>
            <a class="paging next" id="pagingnext" href="#" style="display: none"><span>Next</span></a>
        </div>
    </div>
</div>
<div class="pagewrap right main">@RenderBody()</div>
@section HeaderInsert{@RenderSection("HeaderInsert", false)}
@section JsVarInsert{@RenderSection("JsVarInsert", false)}
@section JsOnLoadInsert{@RenderSection("JsOnLoadInsert", false)}